### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by orta** [NSManchester/nsmanchester.github.com#7]
It would be nice to have someone who has recently released their first app discuss the things that were pleasant, surprising and difficult. What would they have done differently? What can the community do to make that easier for other people?

**Comment by tailec** [comment]
Covered by [@matthew_spear](https://twitter.com/matthew_spear)

**Comment by orta** [comment]
And covered by my blog post http://artsy.github.io/blog/2016/01/30/iOS-Junior-Interviews/
